
sudo: required
services:
    - docker

before:install:
    - docker build -t gtdelgado/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gtdelgado/react-test npm run test

after_success:
    - docker build -t gtdelgado/multi-client ./client
    - docker build -t gtdelgado/multi-nginx ./nginx
    - docker build -t gtdelgado/multi-server ./server
    - docker build -t gtdelgado/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push gtdelgado/multi-client
    - docker push gtdelgado/multi-nginx
    - docker push gtdelgado/multi-server
    - docker push gtdelgado/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-065140640797
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY